CREATE TABLE [dbo].[DATA6222] (
    [DATA6222_ID]     INT          NOT NULL,
    [CAR_ID]          INT          NULL,
    [MANUFACTURER_ID] INT          NOT NULL,
    [DRIVE_TYPE]      VARCHAR (20) NOT NULL,
    [VEHICLE_TYPE]    VARCHAR (20) NOT NULL,
    [SOLD]            BIT          DEFAULT ('FALSE') NULL,
    PRIMARY KEY CLUSTERED ([DATA6222_ID] ASC),
    CHECK ([MANUFACTURER_ID]>=(1)),
    CONSTRAINT [CHK_DriveAndVehicleType] CHECK (([DRIVE_TYPE]='2WD' OR [DRIVE_TYPE]='4WD') AND ([VEHICLE_TYPE]='OFFROAD' OR [VEHICLE_TYPE]='TRUCK' OR [VEHICLE_TYPE]='SUV')),
    FOREIGN KEY ([CAR_ID]) REFERENCES [dbo].[CAR] ([CAR_ID]),
    UNIQUE NONCLUSTERED ([MANUFACTURER_ID] ASC)
);

