CREATE PROCEDURE CAR_DELETE
(
	@CAR_ID INT

)
AS
BEGIN
	INSERT CAR_BACKUP(
	[CAR_ID]
      ,[MANUFACTURER_ID]
      ,[MODEL]
      ,[COLOUR]
      ,[ODOMETER_READING]
      ,[CONDITION_RATING]
      ,[PRICE]
      ,[MECHANIC_ID]
      ,[CLEANER_ID]
      ,[SALESPERSON_ID]
	)
	SELECT 
	  [CAR_ID]
      ,[MANUFACTURER_ID]
      ,[MODEL]
      ,[COLOUR]
      ,[ODOMETER_READING]
      ,[CONDITION_RATING]
      ,[PRICE]
      ,[MECHANIC_ID]
      ,[CLEANER_ID]
      ,[SALESPERSON_ID]
	  FROM CAR WHERE CAR_ID = @CAR_ID

	DELETE FROM CAR
	WHERE CAR_ID = @CAR_ID
END